### ISSUE TITLE
Dashboard Display KPIs based on the active contracts

### ISSUE THREAD

**Issue by YangQiantwx** [akamy-rent/akamy-rent#94]
Please do work for this task in a branch named issue-93.
Make the active contracts, total income, and expense displayed by active contracts data

**Comment by hsmidt** [comment]
I was thinking that this could be done via a Mongo Query in a publication, or else within Tracker based on the contracts publication for users. The latter is probably easier with underscore or [lodash](https://lodash.com/) (Hoku already added lodash, so that would be the better choice).

It'll be three calculations, each one should had been covered in the underscore modules of class (lodash is just like underscore):
- active contracts: filter elements by status and count elements
- total income: filter (username === homeowneremail), map (amount), and reduce (take a sum)
- expense: filter (username === tenantemail), map (amount), and reduce (take a sum)
